In [40]:
import numpy as np

$$
a = \begin{bmatrix}
1 &2 \\
3 &4
\end{bmatrix}
$$

$$
b = \begin{bmatrix}
5 &6 \\
7 &8
\end{bmatrix}
$$

$$
\begin{split}
y& = a \cdot b \\
&=  \begin{bmatrix}
19 &22 \\
 43 &50
\end{bmatrix}
\end{split}
$$


In [41]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)

In [42]:
a

array([[1, 2],
       [3, 4]])

In [43]:
b

array([[5, 6],
       [7, 8]])

In [44]:
np.tensordot(a, b)

array(70)

In [45]:
np.tensordot(a, b, axes=0)

array([[[[ 5,  6],
         [ 7,  8]],

        [[10, 12],
         [14, 16]]],


       [[[15, 18],
         [21, 24]],

        [[20, 24],
         [28, 32]]]])

In [46]:
np.tensordot(a, b, axes=1)

array([[19, 22],
       [43, 50]])

In [47]:
np.tensordot(a, b, axes=2)

array(70)

In [48]:
np.tensordot(np.array([[1,1],[1,1]]),np.array([[2,3],[4,5]]),axes=2)

array(14)

In [72]:
n = 1
c_i = 1
h_i = 5
w_i = 5
x = np.arange(n * c_i * h_i * w_i).reshape(n, c_i, h_i, w_i).astype(np.float32)

In [73]:
c_o = 1
h_k = 2
w_k = 2
W =  np.full(c_o * c_i * h_k * w_k, 2).reshape(c_o, c_i, h_k, w_k).astype(np.float32)

In [74]:
print(x.shape, W.shape)

(1, 1, 5, 5) (1, 1, 2, 2)


In [85]:
result = np.zeros((1,1,4,4), dtype=np.float32)

for nn in range(n):
    for cc_i in range(c_i):
        for cc_o in range(c_o):
            for h in range(h_i - h_k + 1):
                 for w in range(w_i - w_k + 1):
                    for k_h in range(h_k):
                        for k_w in range(w_k):
                            result[nn,cc_i*c_i + cc_o,h,w] += x[nn][cc_i][h+k_h][w+k_w] * W[nn][cc_o][k_h][k_w]

In [86]:
result

array([[[[ 24.,  32.,  40.,  48.],
         [ 64.,  72.,  80.,  88.],
         [104., 112., 120., 128.],
         [144., 152., 160., 168.]]]], dtype=float32)

In [77]:
from chainer.utils import conv

In [79]:
col = conv.im2col_cpu(x, h_k, w_k, 1, 1, 0, 0)

In [80]:
col.shape, W.shape

((1, 1, 2, 2, 4, 4), (1, 1, 2, 2))

In [81]:
col

array([[[[[[ 0.,  1.,  2.,  3.],
           [ 5.,  6.,  7.,  8.],
           [10., 11., 12., 13.],
           [15., 16., 17., 18.]],

          [[ 1.,  2.,  3.,  4.],
           [ 6.,  7.,  8.,  9.],
           [11., 12., 13., 14.],
           [16., 17., 18., 19.]]],


         [[[ 5.,  6.,  7.,  8.],
           [10., 11., 12., 13.],
           [15., 16., 17., 18.],
           [20., 21., 22., 23.]],

          [[ 6.,  7.,  8.,  9.],
           [11., 12., 13., 14.],
           [16., 17., 18., 19.],
           [21., 22., 23., 24.]]]]]], dtype=float32)

In [82]:
W

array([[[[2., 2.],
         [2., 2.]]]], dtype=float32)

In [92]:
W.reshape(1*2*2)


array([2., 2., 2., 2.], dtype=float32)

In [96]:
np.tensordot(col, W,  axes=((1,2), (1,2)) )

array([[[[[[10., 10.]],

          [[14., 14.]],

          [[18., 18.]],

          [[22., 22.]]],


         [[[30., 30.]],

          [[34., 34.]],

          [[38., 38.]],

          [[42., 42.]]],


         [[[50., 50.]],

          [[54., 54.]],

          [[58., 58.]],

          [[62., 62.]]],


         [[[70., 70.]],

          [[74., 74.]],

          [[78., 78.]],

          [[82., 82.]]]],



        [[[[14., 14.]],

          [[18., 18.]],

          [[22., 22.]],

          [[26., 26.]]],


         [[[34., 34.]],

          [[38., 38.]],

          [[42., 42.]],

          [[46., 46.]]],


         [[[54., 54.]],

          [[58., 58.]],

          [[62., 62.]],

          [[66., 66.]]],


         [[[74., 74.]],

          [[78., 78.]],

          [[82., 82.]],

          [[86., 86.]]]]]], dtype=float32)

In [95]:
np.tensordot(col, W,  axes=((1,2,3), (1,2,3)) )

array([[[[ 24.],
         [ 32.],
         [ 40.],
         [ 48.]],

        [[ 64.],
         [ 72.],
         [ 80.],
         [ 88.]],

        [[104.],
         [112.],
         [120.],
         [128.]],

        [[144.],
         [152.],
         [160.],
         [168.]]]], dtype=float32)

In [61]:
np.tensordot(col, W,  axes=((3), (3)) )

array([[[[[[[[ 2.,  2.]]],


           [[[ 6.,  6.]]]],



          [[[[14., 14.]]],


           [[[18., 18.]]]]],




         [[[[[14., 14.]]],


           [[[18., 18.]]]],



          [[[[26., 26.]]],


           [[[30., 30.]]]]]]]], dtype=float32)

In [62]:
np.tensordot(col, W,  axes=((1,2), (1,2)) )

array([[[[[[ 6.,  6.]],

          [[10., 10.]]],


         [[[18., 18.]],

          [[22., 22.]]]],



        [[[[10., 10.]],

          [[14., 14.]]],


         [[[22., 22.]],

          [[26., 26.]]]]]], dtype=float32)

In [71]:
np.tensordot(col, W,  axes=((1,2,3),(1,2,3)))

array([[[[16.],
         [24.]],

        [[40.],
         [48.]]]], dtype=float32)